### ISSUE TITLE
summarize function

### ISSUE THREAD

**Issue by jmcbroom** [CityOfDetroit/crime-viewer#6]
- input: the currently filtered data
- output: some basic statistics (possibly based on what's selected)

**Comment by jessicamcinchak** [comment]
Possible ideas for summary stats:
- [ ] - totalIncidents: sum total number of incidents on map for any given combination of filters
- [ ] - countByKey: feed it array of data and a field name (eg "offense_category"), return count of each unique value in that field
- [ ] - groupAndCount: feed it array of data and two field names, return count of each unique value in that field grouped by another field (eg: types of crime by neighborhood or number of crimes at hour of day by day of the week)
- [ ] - TBD 

Other ideas for comparative analysis? Like, number or percent change in total incidents for this week versus last week.
