### ISSUE TITLE
Crimer Viewer app title is 'React App', icon is React logo

### ISSUE THREAD

**Issue by Tapeless** [CityOfDetroit/crime-viewer#79]
https://github.com/CityOfDetroit/crime-viewer/blob/12725554fc848e492b96619ba9151b2dc6a075e3/public/index.html#L28

https://github.com/CityOfDetroit/crime-viewer/blob/12725554fc848e492b96619ba9151b2dc6a075e3/public/index.html#L13

Should change this to reflect the purpose of the app for end users : ^ )

**Comment by benterova** [comment]
Addressed in #80
